### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by emertechie** [peterkhayes/multisort#1]
I realise bower is considered legacy tech these days, but I work on projects that still require it and I needed multisort in the browser.

I forked this repo to add support in case anyone else needs it: https://github.com/emertechie/multisort

**Comment by peterkhayes** [comment]
I'd accept a PR if you want to create one!

**Comment by emertechie** [comment]
Sure thing: https://github.com/peterkhayes/multisort/pull/2
