### ISSUE TITLE
FR: Number as Parameter

### ISSUE THREAD

**Issue by X-Raym** [peterkhayes/multisort#3]
Hi, I don't think we can have Index (number) as parameter. It seems to only works on Items named property or array key, but not child array index (in case you have a master array containing other arrays).

Let me know if I miss something. thanks :)

**Comment by peterkhayes** [comment]
I'm not sure I understand... can you give me an example snippet?

**Comment by X-Raym** [comment]
Hi,

I use https://www.npmjs.com/package/csv-string package to parse CSV strings,
the results is an **array of arrays** like

```js
var csv_array = [
  ['Cats', 'Dogs', 'Banana'],
  [3, 3, 2],
  [2, 1, 1],
  [1, 2, 3],
]
```

As far as I understand, multi sort allows to sort by name,

```js
multisort(csv_array, ['Dogs', 'Cats']);
```

But I needed a way to make it from column indexes so I tried

```js
multisort(csv_array, [3, 2]);
```

without success.

(I noticed you examples  only shows array of objects, not arrays of arrays, are they spposed to work ?)

Did I miss something ?

**Comment by peterkhayes** [comment]
try `multisort(csv_array, ["3", "2"])`.  This works because `array["1"]` does the same thing as `array[1]`.  Let me know if you need something more!

**Comment by X-Raym** [comment]
Thanks for the tip ! :)
