### ISSUE TITLE
Pure functions - do not modify the input

### ISSUE THREAD

**Issue by MartinMuzatko** [peterkhayes/multisort#4]
Hello! When using `multisort(array, credentials)`, I won't be able to get a return value. Instead the function changes the array. This is not a desired behavior, as I want to re-assign the sorted result.

**Comment by peterkhayes** [comment]
Hi Martin - I did it this way to duplicate the behavior of `[].sort`.  There are a couple of ways to do this.

First, you could copy the array before sorting:
```js
const sorted = myArray.slice()
multisort(sorted)
```

Or, you might check out the `lodash` library. They have an `orderBy` method - check it out [here](https://lodash.com/docs/4.17.4#orderBy). You can even include this method without including the whole `lodash` package, available [on npm](https://www.npmjs.com/package/lodash.orderby).
